spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stecken_rein
    username: stecken_user
    password: stecken_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

server:
  port: 8090