spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stecken_rein
    username: stecken_user
    password: stecken_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090